# -*- coding: utf-8 -*-
"""Copy of medicals_suggestor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cuiunZHHrfsAA49q0kbyMx6FmhvF5aHH
"""

!pip install osmnx geopy

from IPython.display import Javascript
from google.colab import output

def get_location():
    display(Javascript('''
        async function getLocation() {
            return new Promise((resolve, reject) => {
                navigator.geolocation.getCurrentPosition(
                    (position) => {
                        resolve({
                            lat: position.coords.latitude,
                            lon: position.coords.longitude
                        });
                    },
                    (error) => {
                        let errorMessage = "Geolocation error: ";
                        switch (error.code) {
                            case error.PERMISSION_DENIED:
                                errorMessage += "User denied the request for Geolocation.";
                                break;
                            case error.POSITION_UNAVAILABLE:
                                errorMessage += "Location information is unavailable.";
                                break;
                            case error.TIMEOUT:
                                errorMessage += "The request to get user location timed out.";
                                break;
                            default:
                                errorMessage += error.message || "An unknown error occurred.";
                        }
                        reject(errorMessage);
                    }
                );
            });
        }
    '''))

    return output.eval_js("getLocation()")

try:
    location = get_location()
    print("Your Live Location:", location)
except Exception as e:
    print(f"Failed to get location: {e}")

import osmnx as ox
from geopy.distance import geodesic
import pandas as pd

def find_nearest_pharmacies_with_gmaps(user_lat, user_lon, radius=5000):

    tags = {"amenity": "pharmacy"}

    pharmacies = ox.features_from_point(
        (user_lat, user_lon),
        tags=tags,
        dist=radius
    )

    if pharmacies.empty:
        return "No pharmacies found nearby"

    # Filter for Point geometries and drop rows with missing data
    pharmacies = pharmacies[pharmacies.geometry.apply(lambda geom: geom.geom_type == 'Point')]
    pharmacies = pharmacies[["name", "geometry"]].dropna()

    if pharmacies.empty:
        return "No pharmacies found nearby with valid point locations."

    pharmacies["latitude"] = pharmacies.geometry.y
    pharmacies["longitude"] = pharmacies.geometry.x

    user_location = (user_lat, user_lon)

    pharmacies["distance_km"] = pharmacies.apply(
        lambda row: geodesic(
            user_location,
            (row["latitude"], row["longitude"])
        ).km,
        axis=1
    )

    pharmacies = pharmacies.sort_values("distance_km").head(5)

    # Create Google Maps link
    pharmacies["google_maps_link"] = pharmacies.apply(
        lambda row: f"https://www.google.com/maps/dir/{user_lat},{user_lon}/{row['latitude']},{row['longitude']}",
        axis=1
    )

    return pharmacies[["name", "distance_km", "google_maps_link"]]

user_lat = 37.4220
user_lon = -122.0841

find_nearest_pharmacies_with_gmaps(user_lat, user_lon)

